sudo: required
services:
  - docker

dist: trusty

env:
  - SHA=$(git rev-parse --short HEAD)

before_install:
  - docker image build --tag juliocesarmidia/etcd-app:$SHA -f ./etcd-app/Dockerfile ./etcd-app

script:
  - docker container run --rm --entrypoint "" juliocesarmidia/etcd-app:$SHA npm run test

after_success:
  - docker image build --tag juliocesarmidia/etcd-app:$SHA --tag juliocesarmidia/etcd-app:v1.0.0 -f ./etcd-app/Dockerfile ./etcd-app

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker image push juliocesarmidia/etcd-app:v1.0.0
  - docker image push juliocesarmidia/etcd-app:$SHA
