sudo: required
services:
  - docker

dist: trusty

env:
  - SHA=$(git rev-parse --short=7 HEAD)

before_install:
  - |
    docker image build --tag juliocesarmidia/etcd-app:$SHA --tag juliocesarmidia/etcd-app:latest ./etcd-app

script:
  - |
    docker container run --rm \
      --name etcd-app \
      --entrypoint "" \
      juliocesarmidia/etcd-app:$SHA npm run test

after_success:
  - |
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    docker image push juliocesarmidia/etcd-app:latest
    docker image push juliocesarmidia/etcd-app:$SHA
