apiVersion: v1
kind: Pod
metadata:
  labels:
    app: etcd
    etcd_node: etcd1
  name: etcd1
  namespace: default

spec:
  containers:
    - name: etcd1
      image: bitnami/etcd:3-debian-10
      # image: quay.io/coreos/etcd:latest

      # command:
      # - /usr/local/bin/etcd
      # - --name
      # - etcd1
      # - --initial-advertise-peer-urls
      # - http://etcd1:2380
      # - --listen-peer-urls
      # - http://0.0.0.0:2380
      # - --listen-client-urls
      # - http://0.0.0.0:2379
      # - --advertise-client-urls
      # - http://etcd1:2379
      # - --initial-cluster
      # - etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
      # - --initial-cluster-state
      # - new

      env:
        - name: ETCD_NAME
          value: etcd1

        - name: ETCD_INITIAL_ADVERTISE_PEER_URLS
          value: http://etcd1:2380

        - name: ETCD_LISTEN_PEER_URLS
          value: http://0.0.0.0:2380

        - name: ETCD_LISTEN_CLIENT_URLS
          value: http://0.0.0.0:2379

        - name: ETCD_ADVERTISE_CLIENT_URLS
          value: http://etcd1:2379

        - name: ETCD_INITIAL_CLUSTER
          value: etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380

        - name: ETCD_INITIAL_CLUSTER_STATE
          value: new

        - name: ETCD_INITIAL_CLUSTER_TOKEN
          value: etcd-cluster

        - name: ALLOW_NONE_AUTHENTICATION
          value: "yes"

        - name: ETCD_DATA_DIR
          value: /bitnami/etcd/data/

      ports:
        - containerPort: 2379
          name: client-port
          protocol: TCP

        - containerPort: 2380
          name: server-port
          protocol: TCP

      resources:
        requests:
          memory: "128Mi"
          cpu: "150m"

        limits:
          memory: "256Mi"
          cpu: "300m"

---

apiVersion: v1
kind: Service
metadata:
  labels:
    etcd_node: etcd1
  name: etcd1

spec:
  type: ClusterIP

  selector:
    etcd_node: etcd1

  ports:
  - name: client
    port: 2379
    protocol: TCP
    targetPort: client-port

  - name: server
    port: 2380
    protocol: TCP
    targetPort: server-port
