apiVersion: v1
kind: Service
metadata:
  name: etcd-svc
  namespace: default

spec:
  type: ClusterIP

  selector:
    app: etcd

  ports:
    - protocol: TCP
      port: 2379
      targetPort: client-port
