apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd-deployment
  namespace: development
  labels:
    app: etcd-app

spec:
  # replicas: 1
  revisionHistoryLimit: 5

  selector:
    matchLabels:
      app: etcd-app

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 3

  template:
    metadata:
      name: etcd-app
      labels:
        app: etcd-app

    spec:
      containers:
        - name: app
          image: juliocesarmidia/etcd-app:v1.0.0

          ports:
            - containerPort: 8200
              name: etcd-app-port

          env:
            - name: ETCD_HOST
              value: "http://etcd-svc:2379"

            - name: ETCD_CACHE_SECRET
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: ETCD_CACHE_SECRET

            - name: API_PORT
              value: "8200"

          resources:
            requests:
              memory: "128Mi"
              cpu: "150m"

            limits:
              memory: "256Mi"
              cpu: "300m"

          livenessProbe:
            httpGet:
              path: /api/v1/healthcheck
              port: 8200
            initialDelaySeconds: 10
            timeoutSeconds: 30

          readinessProbe:
            httpGet:
              path: /api/v1/healthcheck
              port: 8200
            initialDelaySeconds: 10
            timeoutSeconds: 30

          imagePullPolicy: IfNotPresent

      restartPolicy: Always
