apiVersion: v1
kind: Pod
metadata:
  name: etcd2
  namespace: development
  labels:
    app: etcd
    etcd_pod: etcd2

spec:
  containers:
    - name: etcd2
      image: bitnami/etcd:3-debian-10

      env:
        - name: ETCD_NAME
          value: etcd2

        - name: ETCD_INITIAL_ADVERTISE_PEER_URLS
          value: http://etcd2:2380

        - name: ETCD_LISTEN_PEER_URLS
          value: http://0.0.0.0:2380

        - name: ETCD_LISTEN_CLIENT_URLS
          value: http://0.0.0.0:2379

        - name: ETCD_ADVERTISE_CLIENT_URLS
          value: http://etcd2:2379

        - name: ETCD_INITIAL_CLUSTER
          value: etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380

        - name: ETCD_INITIAL_CLUSTER_STATE
          value: new

        - name: ETCD_INITIAL_CLUSTER_TOKEN
          value: etcd-cluster

        - name: ALLOW_NONE_AUTHENTICATION
          value: "yes"

        - name: ETCD_DATA_DIR
          value: /bitnami/etcd/data/

        - name: ETCD_HEARTBEAT_INTERVAL
          value: "50"

        - name: ETCD_ELECTION_TIMEOUT
          value: "250"

      ports:
        - containerPort: 2379
          name: client-port
          protocol: TCP
        - containerPort: 2380
          name: server-port
          protocol: TCP

      resources:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "128Mi"
          cpu: "200m"

---

apiVersion: v1
kind: Service
metadata:
  name: etcd2
  namespace: development

spec:
  type: ClusterIP

  selector:
    etcd_pod: etcd2

  ports:
  - name: client
    port: 2379
    protocol: TCP
    targetPort: client-port

  - name: server
    port: 2380
    protocol: TCP
    targetPort: server-port
