apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: etcd-hpa
  namespace: development

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: etcd-deployment

  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
